[project]
name = "api-rest"
version = "1.1.0"
description = "REST API with Flask, Connexion, MongoDB"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "a2wsgi==1.10.10",
    "anyio==4.13.0",
    "asgiref==3.11.1",
    "attrs==26.1.0",
    "bcrypt==5.0.0",
    "blinker==1.9.0",
    "certifi==2026.4.22",
    "charset-normalizer==3.4.7",
    "click==8.3.3",
    "clickclick==20.10.2",
    "colorama==0.4.6",
    "connexion==3.3.0",
    "dnspython==2.8.0",
    "flask==3.1.3",
    "flask-jwt-extended==4.7.1",
    "flask-limiter==4.1.1",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpproblem==0.2.0",
    "httptools>=0.7.1",
    "httpx==0.28.1",
    "idna==3.13",
    "inflection==0.5.1",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "jsonschema==4.26.0",
    "jsonschema-specifications==2024.10.1",
    "markupsafe==3.0.3",
    "packaging==26.2",
    "prometheus-client==0.25.0",
    "py-healthcheck==1.10.1",
    "pyjwt==2.12.1",
    "pymongo==4.17.0",
    "python-dotenv==1.2.2",
    "python-multipart==0.0.27",
    "pyyaml==6.0.3",
    "referencing==0.37.0",
    "requests==2.33.1",
    "rpds-py>=0.30.0",
    "sniffio==1.3.1",
    "starlette==1.0.0",
    "swagger-ui-bundle==1.1.0",
    "typing-extensions==4.15.0",
    "urllib3==2.7.0",
    "uvicorn==0.46.0",
    "watchfiles>=1.1.1",
    "werkzeug==3.1.8",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
pythonpath = ["app"]
testpaths = ["tests"]
